package net.thechance.mena.faith.domain.entity

data class Surah(
    val id: Int,
    val order: SurahOrder,
    val name: String,
    val ayahCount: Int,
) {
    enum class SurahOrder(val order: Int,val isMakkia: Boolean ) {
        AlFatihah(order = 1,isMakkia = true),
        AlBaqarah(order = 2, isMakkia = false),
        AalImran(order = 3, isMakkia = false),
        AnNisa(order = 4, isMakkia = false),
        AlMaidah(order = 5, isMakkia = false),
        AlAnam(order = 6,isMakkia = true),
        AlAraf(order = 7,isMakkia = true),
        AlAnfal(order = 8,isMakkia = false),
        AtTawbah(order = 9,isMakkia = false),
        Yunus(order = 10,isMakkia = true),
        Hud(order = 11,isMakkia = true),
        Yusuf(order = 12,isMakkia = true),
        ArRad(order = 13,isMakkia = false),
        Ibrahim(order = 14,isMakkia = true),
        AlHijr(order = 15,isMakkia = true),
        AnNahl(order = 16,isMakkia = true),
        AlIsra(order = 17,isMakkia = true),
        AlKahf(order = 18,isMakkia = true),
        Maryam(order = 19,isMakkia = true),
        TaHa(order = 20,isMakkia = true),
        AlAnbiya(order = 21,isMakkia = true),
        AlHajj(order = 22, isMakkia = false),
        AlMuminun(order = 23,isMakkia = true),
        AnNur(order = 24,isMakkia = false),
        AlFurqan(order = 25,isMakkia = true),
        AshShuara(order = 26,isMakkia = true),
        AnNaml(order = 27,isMakkia = true),
        AlQasas(order = 28,isMakkia = true),
        AlAnkabut(order = 29,isMakkia = true),
        ArRum(order = 30,isMakkia = true),
        Luqman(order = 31,isMakkia = true),
        AsSajdah(order = 32,isMakkia = true),
        AlAhzab(order = 33,isMakkia = false),
        Saba(order = 34,isMakkia = true),
        Fatir(order = 35,isMakkia = true),
        YaSin(order = 36,isMakkia = true),
        AsSaffat(order = 37,isMakkia = true),
        Sad(order = 38,isMakkia = true),
        AzZumar(order = 39,isMakkia = true),
        Ghafir(order = 40,isMakkia = true),
        Fussilat(order = 41,isMakkia = true),
        AshShura(order = 42,isMakkia = true),
        AzZukhruf(order = 43,isMakkia = true),
        AdDukhan(order = 44,isMakkia = true),
        AlJathiya(order = 45,isMakkia = true),
        AlAhqaf(order = 46,isMakkia = true),
        Muhammad(order = 47,isMakkia = false),
        AlFath(order = 48,isMakkia = false),
        AlHujurat(order = 49,isMakkia = false),
        Qaf(order = 50,isMakkia = true),
        AzZariyat(order = 51,isMakkia = true),
        AtTur(order = 52,isMakkia = true),
        AnNajm(order = 53,isMakkia = true),
        AlQamar(order = 54,isMakkia = true),
        ArRahman(order = 55,isMakkia = false),
        AlWaqiah(order = 56,isMakkia = true),
        AlHadid(order = 57,isMakkia = false),
        AlMujadilah(order = 58,isMakkia = false),
        AlHashr(order = 59,isMakkia = false),
        AlMumtahanah(order = 60,isMakkia = false),
        AsSaff(order = 61,isMakkia = false),
        AlJumuah(order = 62,isMakkia = false),
        AlMunafiqun(order = 63,isMakkia = false),
        AtTaghabun(order = 64,isMakkia = false),
        AtTalaq(order = 65,isMakkia = false),
        AtTahrim(order = 66,isMakkia = false),
        AlMulk(order = 67,isMakkia = true),
        AlQalam(order = 68,isMakkia = true),
        AlHaqqah(order = 69,isMakkia = true),
        AlMaarij(order = 70,isMakkia = true),
        Nuh(order = 71,isMakkia = true),
        AlJinn(order = 72,isMakkia = true),
        AlMuzzammil(order = 73,isMakkia = true),
        AlMuddathir(order = 74,isMakkia = true),
        AlQiyamah(order = 75,isMakkia = true),
        AlInsan(order = 76,isMakkia = false),
        AlMursalat(order = 77,isMakkia = true),
        AnNaba(order = 78,isMakkia = true),
        AnNaziat(order = 79,isMakkia = true),
        Abasa(order = 80,isMakkia = true),
        AtTakwir(order = 81,isMakkia = true),
        AlInfitar(order = 82,isMakkia = true),
        AlMutaffifin(order = 83,isMakkia = true),
        AlInshiqaq(order = 84,isMakkia = true),
        AlBuruj(order = 85,isMakkia = true),
        AtTariq(order = 86,isMakkia = true),
        AlAla(order = 87,isMakkia = true),
        AlGhashiyah(order = 88,isMakkia = true),
        AlFajr(order = 89,isMakkia = true),
        AlBalad(order = 90,isMakkia = true),
        AshShams(order = 91,isMakkia = true),
        AlLayl(order = 92,isMakkia = true),
        AdDuha(order = 93,isMakkia = true),
        AshSharh(order = 94,isMakkia = true),
        AtTin(order = 95,isMakkia = true),
        AlAlaq(order = 96,isMakkia = true),
        AlQadr(order = 97,isMakkia = true),
        AlBayyinah(order = 98,isMakkia = false),
        AzZalzalah(order = 99,isMakkia = false),
        AlAdiyat(order = 100,isMakkia = true),
        AlQariah(order = 101,isMakkia = true),
        AtTakathur(order = 102,isMakkia = true),
        AlAsr(order = 103,isMakkia = true),
        AlHumazah(order = 104,isMakkia = true),
        AlFil(order = 105,isMakkia = true),
        Quraish(order = 106,isMakkia = true),
        AlMaun(order = 107,isMakkia = true),
        AlKawthar(order = 108,isMakkia = true),
        AlKafirun(order = 109,isMakkia = true),
        AnNasr(order = 110,isMakkia = false),
        AlMasad(order = 111,isMakkia = true),
        AlIkhlas(order = 112,isMakkia = true),
        AlFalaq(order = 113,isMakkia = true),
        AnNas(order = 114,isMakkia = true),
    }
}
